package com.jzallas.backdrop.javascript.webview

import android.webkit.WebResourceRequest
import android.webkit.WebView
import androidx.webkit.WebViewClientCompat
import androidx.webkit.WebViewAssetLoader
import androidx.webkit.WebViewAssetLoader.DEFAULT_DOMAIN

/**
 * Facilitates injecting of javascript assets into any given [WebView].
 */
class ScriptInjector(private val assetLoader: WebViewAssetLoader) {

  /**
   * Transforms the provided [scripts] into a block of html.
   * The block of html can be used with [WebView.loadDataWithBaseURL] to kick off web requests for the script assets.
   */
  fun inject(vararg scripts: String): String {
    return scripts.joinToString(System.lineSeparator()) {
      """<script type="text/javascript" src="https://$DEFAULT_DOMAIN/assets/$it"></script>"""
    }
  }

  /**
   * Intercepts requests that were generated by [inject].
   * Use this with [WebViewClientCompat.shouldInterceptRequest] to load the injected asset.
   */
  fun intercept(request: WebResourceRequest) =
    assetLoader.shouldInterceptRequest(request.url)
}
