name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11
    - run: npm ci --prefix ./web
    - run: npm build --prefix ./web
    - run: ./gradlew clean
    - run: ./gradlew test
    - run: ./gradlew build
