name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11
    - name: Downloading web dependencies
      run: npm ci --prefix ./web
    - name: Building webpack
      run: npm build --prefix ./web
    - name: Test
      run: ./gradlew clean test
    - name: Build
      run: ./gradlew clean build
